### ISSUE TITLE
"No module named 'ioctl_opt'" on running tests

### ISSUE THREAD

**Issue by wimrijnders** [Idein/py-videocore6#39]
Hi there, after installing and trying to run the tests I get:

```
Failure: ModuleNotFoundError (No module named 'ioctl_opt') ... ERROR
```

And all tests appear to fail.
Any idea what's going on? (python noob)

**Comment by Terminus-IMRC** [comment]
I suspect you cloned the repository instead of [installing directly with git](https://github.com/Idein/py-videocore6#installation). In this case, you should manually install the `ioctl-opt` Python package.  Please run `pip3 install --user 'ioctl-opt >= 1.2'` in your shell.

**Comment by Terminus-IMRC** [comment]
Also, install NumPy with `pip3 install --user numpy` if it's missing.

**Comment by wimrijnders** [comment]
Not sure what happened here. Now, every time I run `pip3`, I get this:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line
33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip._internal import main
  File "/usr/lib/python3/dist-packages/pip/_internal/__init__.py",
line 19, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line
64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line
36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py",
line 9, in <module>
...
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in
spec_from_file_location
zlib.error: Error -3 while decompressing data: invalid distance too far back
```

On 5/15/20, Yukimasa Sugizaki <notifications@github.com> wrote:
> Also, install NumPy with `pip3 install --user numpy` if it's missing.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Idein/py-videocore6/issues/39#issuecomment-629163479


-- 
Met vriendelijke groet,

Wim Rijnders
http://axizo.nl

**Comment by Terminus-IMRC** [comment]
Your pip seems to be broken. Does anything change after running the commands below in your shell?

```bash
$ sudo apt update
$ sudo apt install --reinstall python3-pip
$ python3 -m pip install --user --upgrade pip
$ python3 -m pip install --user --upgrade ioctl-opt numpy
```

If things don't go well, then you might be needed to replace your SD card because SD cards are easily broken.

**Comment by wimrijnders** [comment]
@Terminus-IMRC  thanks for helping out, but no luck here.

Searching online, I found that this is a common problem with pythong 3.8. However, I not found a satisfactory solution yet. Will try another pi.

**Comment by wimrijnders** [comment]
On the Pi4 it worked in one go; however, tests are failing.

I will assume that the sd-card is just bad. I'll open another issue for the failing tests.

**Comment by Terminus-IMRC** [comment]
Please note that py-videocore6 only works on Raspberry Pi 4, as noted in [README.md](https://github.com/Idein/py-videocore6/blob/master/README.md). For Raspberry Pi 1/2/3/Zero, use [py-videocore](http://github.com/nineties/py-videocore) instead.

**Comment by wimrijnders** [comment]
OK, noted. I will test that as soon as I get a new SD-card configured.

But `pip3` should still work.

On 5/18/20, Yukimasa Sugizaki <notifications@github.com> wrote:
> Please note that py-videocore6 only works on Raspberry Pi 4, as noted in
> [README.md](https://github.com/Idein/py-videocore6/blob/master/README.md).
> For Raspberry Pi 1/2/3/Zero, use
> [py-videocore](http://github.com/nineties/py-videocore) instead.
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/Idein/py-videocore6/issues/39#issuecomment-630108484


-- 
Met vriendelijke groet,

Wim Rijnders
http://axizo.nl
